[dev]
port = 3000

[site]
code_highlighting = true
sitemap_base_url = "https://rustyink.cli.rs"

[meta]
title = "Rusty!nk"
description = "Blazing fast static site generator written in Rust"

[navigation]
links = [
    { label = "~/", url = "/" },
    { label = "Twitter", url = "https://twitter.com/arjunz" },
    { label = "About", url = "/about" },
]
